<?php
namespace Chamilo\Core\Repository\Implementation\Picasa\Table\ExternalObjectGallery;

use Chamilo\Core\Repository\External\Table\ExternalObjectGallery\DefaultExternalObjectGalleryTablePropertyModel;

class ExternalObjectGalleryObjectTablePropertyModel extends DefaultExternalObjectGalleryTablePropertyModel
{
}
