<?php
namespace Chamilo\Core\Install;

/*
 * DO NOT EDIT THIS FILE ! IT CONTAINS DEFAULT VALUES FOR CLI INSTALL. you can pass other values by providing your own
 * config file to the CLI installer using --config flag Example : php script/chamilo.php install
 * --configuration=my_config_file.php
 */
$values = array();
$values['storage_type'] = 'mdb2';
$values['database_driver'] = 'mysqli';
$values['database_host'] = 'localhost';
$values['database_name'] = 'chamilo';
$values['database_overwrite'] = true;
$values['database_username'] = 'root';
$values['database_password'] = '';

$values['platform_language'] = 'en';

$values['admin_email'] = '';
$values['admin_surname'] = '';
$values['admin_firstname'] = '';
$values['admin_phone'] = '';
$values['admin_username'] = 'admin';
$values['admin_password'] = 'admin';

$values['platform_name'] = 'Chamilo LCMS Connect';
$values['organization_name'] = '';
$values['organization_url'] = 'www.chamilo.org';

$values['self_reg'] = '0';

$values['hashing_algorithm'] = 'sha1';

$values['external_instance'] = array();
$values['install'] = array();
$values['content_object'] = array();

$values['install']['Chamilo\Core\Admin'] = true;
$values['install']['Chamilo\Core\Group'] = true;
$values['install']['Chamilo\Core\Help'] = true;
$values['install']['Chamilo\Core\Home'] = true;
$values['install']['Chamilo\Core\Install'] = true;
$values['install']['Chamilo\Core\Lynx'] = true;
$values['install']['Chamilo\Core\Menu'] = true;
$values['install']['Chamilo\Core\Metadata'] = true;
$values['install']['Chamilo\Core\Reporting'] = true;
$values['install']['Chamilo\Core\Repository'] = true;
$values['install']['Chamilo\Core\Rights'] = true;
$values['install']['Chamilo\Core\Tracking'] = true;
$values['install']['Chamilo\Core\User'] = true;

/* replace XXXXX by a package namespace
$values['install']['XXXXX'] = true;
$values['install']['XXXXX'] = true;
$values['install']['XXXXX'] = true;
$values['install']['XXXXX'] = true;
$values['install']['XXXXX'] = true;

$values['install']['application\weblcms'] = true;
$values['content_object']['core\repository\content_object\announcement'] = true;
$values['content_object']['core\repository\content_object\assessment'] = true;
$values['content_object']['core\repository\content_object\assessment_match_numeric_question'] = true;
$values['content_object']['core\repository\content_object\assessment_match_text_question'] = true;
$values['content_object']['core\repository\content_object\assessment_matching_question'] = true;
$values['content_object']['core\repository\content_object\assessment_matrix_question'] = true;
$values['content_object']['core\repository\content_object\assessment_multiple_choice_question'] = true;
$values['content_object']['core\repository\content_object\assessment_open_question'] = true;
$values['content_object']['core\repository\content_object\assessment_rating_question'] = true;
$values['content_object']['core\repository\content_object\assessment_select_question'] = true;
$values['content_object']['core\repository\content_object\assignment'] = true;
$values['content_object']['core\repository\content_object\blog'] = true;
$values['content_object']['core\repository\content_object\blog_item'] = true;
$values['content_object']['core\repository\content_object\bookmark'] = true;
$values['content_object']['core\repository\content_object\calendar_event'] = true;
$values['content_object']['core\repository\content_object\dailymotion'] = true;
$values['content_object']['core\repository\content_object\description'] = true;
$values['content_object']['core\repository\content_object\document'] = true;
$values['content_object']['core\repository\content_object\event'] = true;
$values['content_object']['core\repository\content_object\external_calendar'] = true;
$values['content_object']['core\repository\content_object\feedback'] = true;
$values['content_object']['core\repository\content_object\file'] = true;
$values['content_object']['core\repository\content_object\fill_in_blanks_question'] = true;
$values['content_object']['core\repository\content_object\forum'] = true;
$values['content_object']['core\repository\content_object\forum_topic'] = true;
$values['content_object']['core\repository\content_object\glossary'] = true;
$values['content_object']['core\repository\content_object\glossary_item'] = true;
$values['content_object']['core\repository\content_object\handbook'] = true;
$values['content_object']['core\repository\content_object\handbook_item'] = true;
$values['content_object']['core\repository\content_object\handbook_topic'] = true;
$values['content_object']['core\repository\content_object\hotpotatoes'] = true;
$values['content_object']['core\repository\content_object\hotspot_question'] = true;
$values['content_object']['core\repository\content_object\indicator'] = true;
$values['content_object']['core\repository\content_object\introduction'] = true;
$values['content_object']['core\repository\content_object\learning_path'] = true;
$values['content_object']['core\repository\content_object\learning_path_item'] = true;
$values['content_object']['core\repository\content_object\link'] = true;
$values['content_object']['core\repository\content_object\match_question'] = true;
$values['content_object']['core\repository\content_object\mediamosa'] = true;
$values['content_object']['core\repository\content_object\note'] = true;
$values['content_object']['core\repository\content_object\ordering_question'] = true;
$values['content_object']['core\repository\content_object\page'] = true;
$values['content_object']['core\repository\content_object\peer_assessment'] = true;
$values['content_object']['core\repository\content_object\personal_message'] = true;
$values['content_object']['core\repository\content_object\physical_location'] = true;
$values['content_object']['core\repository\content_object\portfolio'] = true;
$values['content_object']['core\repository\content_object\portfolio_item'] = true;
$values['content_object']['core\repository\content_object\rss_feed'] = true;
$values['content_object']['core\repository\content_object\scorm_item'] = true;
$values['content_object']['core\repository\content_object\slideshare'] = true;
$values['content_object']['core\repository\content_object\soundcloud'] = true;
$values['content_object']['core\repository\content_object\system_announcement'] = true;
$values['content_object']['core\repository\content_object\task'] = true;
$values['content_object']['core\repository\content_object\template'] = true;
$values['content_object']['core\repository\content_object\twitter_search'] = true;
$values['content_object']['core\repository\content_object\vimeo'] = true;
$values['content_object']['core\repository\content_object\webpage'] = true;
$values['content_object']['core\repository\content_object\wiki'] = true;
$values['content_object']['core\repository\content_object\wiki_page'] = true;
$values['content_object']['core\repository\content_object\youtube'] = true;

*/
