<?php
namespace Chamilo\Core\Repository\Implementation\Photobucket\Table\ExternalObjectGallery;

use Chamilo\Core\Repository\External\Table\ExternalObjectGallery\DefaultExternalObjectGalleryTablePropertyModel;

class ExternalObjectGalleryTablePropertyModel extends DefaultExternalObjectGalleryTablePropertyModel
{
}
