<?php

namespace Chamilo\Application\Weblcms\Bridge\Assignment\Table\Entity\User;

use Chamilo\Core\User\Storage\DataClass\User;

/**
 *
 * @package Chamilo\Core\Repository\ContentObject\Assignment\Integration\Chamilo\Core\Repository\ContentObject\LearningPath\Table\Entity
 * @author Hans De Bisschop <hans.de.bisschop@ehb.be>
 * @author Magali Gillard <magali.gillard@ehb.be>
 * @author Eduard Vossen <eduard.vossen@ehb.be>
 */
class EntityTableCellRenderer
    extends \Chamilo\Application\Weblcms\Bridge\Assignment\Table\Entity\EntityTableCellRenderer
{
    public function render_cell($column, $entity)
    {
        switch (true)
        {
            case ($column->get_name() == User::PROPERTY_FIRSTNAME || $column->get_name() == User::PROPERTY_LASTNAME):
                if($this->canViewEntity($entity)) {
                    return '<a href="' . $this->getEntityUrl($entity) . '">' . $entity[$column->get_name()] . '</a>';
                } else {
                    return $entity[$column->get_name()];
                }
                break;
        }

        return parent::render_cell($column, $entity); // TODO: Change the autogenerated stub
    }
}