var changed=!1,orgtxt="",EQUATION_ENGINE="http://latex.codecogs.com";function cleartext(){var a=document.getElementById("latex_formula");a.value="";a.focus();changed=!1;document.getElementById("renderbutton").className="greybutton"}function textchanged(){var a=getEquationStr();a!=orgtxt&&(orgtxt=a,document.getElementById("renderbutton").className="bluebutton",changed=!0)}
function formatchanged(){var a=!1,b=document.getElementById("format");if(b)switch(b.value){case "gif":a=!1;break;case "png":a=!1;break;case "pdf":a=!0;break;case "swf":a=!0}document.getElementById("dpi").disabled=a;document.getElementById("dpi").readonly=a;changed=!0;renderEqn()}
function addText(a,b,c){myField=a.getElementById(b);if(a.selection)myField.focus(),sel=a.selection.createRange(),sel.text=c;else{a=myField.scrollTop;if(myField.selectionStart||"0"==myField.selectionStart){var b=myField.selectionStart,e=myField.selectionEnd,f=b+c.length;myField.value=myField.value.substring(0,b)+c+myField.value.substring(e,myField.value.length);pos=c.length+e-b;myField.selectionStart=f;myField.selectionEnd=f;myField.focus();myField.setSelectionRange(b+pos,b+pos)}else myField.value+=
c;myField.scrollTop=a}}
function insertText(a,b,c){var e=null==c?b:c;textchanged();1E3==b&&(b=a.length-1);void 0==b&&(a+=" ",b=a.length);myField=document.getElementById("latex_formula");if(document.selection){myField.focus();var f=document.selection.createRange(),d=myField.value.length+1;for(theCaret=f.duplicate();theCaret.parentElement()==myField&&1==theCaret.move("character",1);)--d;d=d-myField.value.split("\n").length+1;("left"==a.substring(1,5)||"{"==a.substring(e-1,e))&&f.text.length?(ins_point="left"==a.substring(1,
5)?7:e,null==c?b=a.length+f.text.length+1:c<b&&(b+=f.text.length),f.text=a.substring(0,ins_point)+f.text+a.substr(ins_point)):f.text=a;a=myField.createTextRange();a.collapse(!0);a.moveEnd("character",d+b);a.moveStart("character",d+b);a.select()}else if(myField.selectionStart||"0"==myField.selectionStart){var d=myField.selectionStart,f=myField.selectionEnd,g=d+a.length;if(("left"==a.substring(1,5)||"{"==a.substr(e-1,1))&&f>d)ins_point="left"==a.substring(1,5)?7:e,null==c?b=a.length+f-d+1:c<b&&(b+=
f-d),a=a.substring(0,ins_point)+myField.value.substring(d,f)+a.substr(ins_point);myField.value=myField.value.substring(0,d)+a+myField.value.substring(f,myField.value.length);myField.selectionStart=g;myField.selectionEnd=g;myField.focus();myField.setSelectionRange(d+b,d+b)}else myField.value+=a;myField.focus()}
function getEquationStr(){var a=document.getElementById("latex_formula").value,a=a.replace(/^\s+|\s+$/g,""),a=a.replace(/\s+/g," "),b=document.getElementById("fontsize");b&&(b=b.options[b.selectedIndex].value,""!=b&&(a=b+" "+a));document.getElementById("compressed").checked&&(a="\\inline "+a);document.getElementById("dpi")&&(b=document.getElementById("dpi").value,"100"!=b&&(a="\\"+b+"dpi "+a));document.getElementById("bg")&&(b=document.getElementById("bg").value,"transparent"!=b&&(a="\\bg_"+b+" "+
a));return a}var initmessage=!0;function processEquationChange(){initmessage?initmessage=!1:document.getElementById("equationcomment").innerHTML=""}
function renderEqn(){if(changed){var a=document.getElementById("latex_formula").value,a=a.replace(/^\s+|\s+$/g,"");if(0!=a.length){var b=0;for(i=0;i<a.length;i++)switch(a[i]){case "{":b++;break;case "}":b--}if(0==b){document.getElementById("renderbutton").className="greybutton";var a=document.getElementById("latex_formula").value,b=document.getElementById("history"),c=b.length;b.length=c+1;b.options[c].text=a.substr(0,15);b.options[c].value=a;b.options[c].title=a;b=document.getElementById("equationview");
a=getEquationStr();a=a.replace(/(\r\n|[\r\n])/g," ");sval=a.replace(/"/g,'\\"');if(document.getElementById("format"))var e=document.getElementById("format").selectedIndex,c=document.getElementById("format").options[e].value;else e=0,c="gif";switch(e){case 0:case 1:e=document.getElementById("equationcomment");e.innerHTML='Rendering Equation <img src="http://www.codecogs.com/components/equationeditor/images/wait.gif" width="13" height ="13"/>';b.onload=processEquationChange;b.src=EQUATION_ENGINE+"/"+
c+".latex?"+a;changed=!1;break;case 2:b.onload="";b.src="http://www.codecogs.com/components/equationeditor/images/pdf.jpg";document.getElementById("download").src="http://www.codecogs.com/pdf.latex?"+a;e=document.getElementById("equationcomment");e.innerHTML='<br/><a target="download" href="http://www.codecogs.com/pdf.latex?'+sval+'"><strong>Click here if the PDF does not downloading.</strong></a>';break;case 3:b.onload="",b.src="http://www.codecogs.com/components/equationeditor/images/spacer.gif",
document.getElementById("equationcomment"),AC_FL_RunContent("codebase","http://download.macromedia.com/pub/shockwave/cabs/flash/swflash.cab#version=8,0,0,0","width","600","height","100","src","http://www.codecogs.com/swf.latex?"+a,"quality","high","pluginspage","http://www.macromedia.com/go/getflashplayer","align","top","scale","showall","wmode","window","devicefont","false","bgcolor","#ffffff","menu","true","allowFullScreen","true","movie",EQUATION_ENGINE+"/swf.latex?"+a),changed=!1}}else e=document.getElementById("equationcomment"),
e.innerHTML=0>b?"<br/><span class=\"orange\">You have more <strong>closed '}' brackets</strong> than open '{' brackets</span>":"<br/><span class=\"orange\">You have more <strong>open '{' brackets</strong> than closed '}' brackets</span>"}}}var auton=0;function renderCountdown(){0<auton?(auton--,setTimeout("renderCountdown()",100)):renderEqn(null)}function autorenderEqn(a){0<auton&&0<a?auton=a:(auton=a,renderCountdown())}
function addfavorite(a){text=document.getElementById("latex_formula").value;var a=document.getElementById(a),b=a.selectedIndex;if(0==b||!confirm("Click Yes to replace the current equation or 'Cancel' to add a new equation")){var c=prompt("Please enter a short name for this equation:","");if(null==c||""==c)c=text.substr(0,15);b=a.length;a.length=b+1;a.options[b].text=c}a.options[b].value=text;a.options[b].title=text;document.cookie="eq_"+escape(c.replace(/\+/g,"&plus;").replace(/\s/g,"&space;"))+"="+
escape(text.replace(/\+/g,"&plus;"))+"; path=/"}function deletefavorite(a){var a=document.getElementById(a),b=a.selectedIndex;if(0<b){name=a.options[b].text;var c=new Date;c.setTime(c.getTime()-1);document.cookie="eq_"+escape(name.replace(/\+/g,"&plus;").replace(/\s/g,"&space;"))+"=; expires="+c.toGMTString()+"; path=/";a.options[b]=null}}
function makeEquationsMatrix(a,b,c){void 0==b&&(b=!1);void 0==c&&(b=!1);var e="\\begin{"+a+(b?"":"*")+"}",c="\n &"+(b?" ":"= ")+(c?"\\text{ if } x=  ":""),f="\n\\end{"+a+(b?"":"*")+"}",d=0,d=prompt("Enter the number of lines:","");if(""!=d&&null!=d&&(n=parseInt(d),!isNaN(n))){for(d=1;d<=n-1;d++)e+=c+"\\\\ ";insertText(e+c+f,a.length+(b?0:1)+9)}}
function makeArrayMatrix(a,b,c){var e=b+"\\begin{"+a+"matrix}",f="\n",c="\n\\end{"+a+"matrix}"+c,d=0,d=prompt('Enter the array dimensions separated by a comma (e.g. "2,3" for 2 rows and 3 columns):',"");if(""!=d&&null!=d&&(d=d.split(","),m=parseInt(d[0]),n=parseInt(d[1]),!isNaN(m)&&!isNaN(n))){for(d=2;d<=n;d++)f+=" & ";for(d=1;d<=m-1;d++)e=e+f+"\\\\ ";insertText(e+f+c,a.length+b.length+15)}}
function hover(a,b){div=document.getElementById("hover");div.innerHTML='<img src="http://www.codecogs.com/gif.latex?\\200dpi '+a.title+'"/>';document.all?(div.style.top=event.clientY-10+"px",div.style.left=event.clientX+20+"px"):(b||(b=window.event),div.style.top=b.pageY-10+"px",div.style.left=b.pageX+20+"px");div.style.display="block";a.onmouseout=function(){document.getElementById("hover").style.display="none"}}function iObject(){this.i;return this}var myObject=new iObject;myObject.i=0;
var myObject2=new iObject;myObject2.i=0;store_text=[""];function countclik(a){a=a.value;if(0==myObject.i||store_text[myObject.i]!=a)myObject.i++,store_text[myObject.i]=a;myObject2.i=0;document.getElementById("redobutton").src="http://www.codecogs.com/images/buttons/redo-x.gif";document.getElementById("undobutton").src="http://www.codecogs.com/images/buttons/undo.gif"}
function undo(a){tag=document.getElementById(a);myObject2.i<myObject.i?(myObject2.i++,myObject2.i==myObject.i&&(document.getElementById("undobutton").src="http://www.codecogs.com/images/buttons/undo-x.gif"),document.getElementById("redobutton").src="http://www.codecogs.com/images/buttons/redo.gif"):alert("Finish Undo Action");a=store_text.length;a-=myObject2.i;tag.value=store_text[a]?store_text[a]:store_text[0];tag.focus()}
function redo(a){tag=document.getElementById(a);1<myObject2.i?(myObject2.i--,1==myObject2.i&&(document.getElementById("redobutton").src="http://www.codecogs.com/images/buttons/redo-x.gif"),document.getElementById("undobutton").src="http://www.codecogs.com/images/buttons/undo.gif"):alert("Finish Redo Action");a=store_text.length;a-=myObject2.i;tag.value=store_text[a]?store_text[a]:store_text[0];tag.focus()}
function updateOpener(a,b){if(""!=a){var c;if("phpBB"==b)c=getEquationStr(),c="[tex]"+c+"[/tex]\n";else if("html"==b)c=getEquationStr(),c='<img src="'+EQUATION_ENGINE+"/gif.latex?"+escape(c)+'" />';else{c=document.getElementById("latex_formula").value;var e=document.getElementById("fontsize");e&&2!=e.selectedIndex&&(c=e.options[e.selectedIndex].value+" "+c);document.getElementById("inline").checked?(document.getElementById("compressed").checked||(c="\\displaystyle "+c),c="$"+c+"$ "):(document.getElementById("compressed").checked&&
(c="\\inline "+c),c="\\["+c+"\\]\n")}addText(window.opener.document,a,c)}else{c=document.getElementById("latex_formula").value;(e=document.getElementById("fontsize"))&&2!=e.selectedIndex&&(c=e.options[e.selectedIndex].value+" "+c);if(0==c.length)return alert(FCKLang.EquationErrNoEqn),!1;document.getElementById("inline").checked?(document.getElementById("compressed").checked||(c="\\displaystyle "+c),c="\\f$"+c+"\\f$ "):(document.getElementById("compressed").checked&&(c="\\inline "+c),c="\\f["+c+"\\f]\n");
if(eSelected&&eSelected._fckequation==c)return!0;c=c.replace(/(\r\n|[\r\n])/g," ");FCKEquation.Add(c)}return!0};