var isIE=-1!=navigator.appVersion.indexOf("MSIE")?!0:!1,isWin=-1!=navigator.appVersion.toLowerCase().indexOf("win")?!0:!1,isOpera=-1!=navigator.userAgent.indexOf("Opera")?!0:!1;
function ControlVersion(){var a,d;try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.7"),a=d.GetVariable("$version")}catch(f){}if(!a)try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.6"),a="WIN 6,0,21,0",d.AllowScriptAccess="always",a=d.GetVariable("$version")}catch(b){}if(!a)try{d=new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),a=d.GetVariable("$version")}catch(g){}if(!a)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash.3"),a="WIN 3,0,18,0"}catch(e){}if(!a)try{new ActiveXObject("ShockwaveFlash.ShockwaveFlash"),
a="WIN 2,0,0,11"}catch(c){a=-1}return a}
function GetSwfVer(){var a=-1;if(null!=navigator.plugins&&0<navigator.plugins.length){if(navigator.plugins["Shockwave Flash 2.0"]||navigator.plugins["Shockwave Flash"]){var a=navigator.plugins["Shockwave Flash"+(navigator.plugins["Shockwave Flash 2.0"]?" 2.0":"")].description.split(" "),d=a[2].split("."),f=d[0],d=d[1],b=a[3];""==b&&(b=a[4]);"d"==b[0]?b=b.substring(1):"r"==b[0]&&(b=b.substring(1),0<b.indexOf("d")&&(b=b.substring(0,b.indexOf("d"))));a=f+"."+d+"."+b}}else-1!=navigator.userAgent.toLowerCase().indexOf("webtv/2.6")?
a=4:-1!=navigator.userAgent.toLowerCase().indexOf("webtv/2.5")?a=3:-1!=navigator.userAgent.toLowerCase().indexOf("webtv")?a=2:isIE&&(isWin&&!isOpera)&&(a=ControlVersion());return a}
function DetectFlashVer(a,d,f){versionStr=GetSwfVer();if(-1==versionStr)return!1;if(0!=versionStr){isIE&&isWin&&!isOpera?(tempArray=versionStr.split(" "),tempString=tempArray[1],versionArray=tempString.split(",")):versionArray=versionStr.split(".");var b=versionArray[0],g=versionArray[1],e=versionArray[2];return b>parseFloat(a)||b==parseFloat(a)&&(g>parseFloat(d)||g==parseFloat(d)&&e>=parseFloat(f))?!0:!1}}function AC_AddExtension(a){return a}
function AC_Generateobj(a,d,f){var a="<embed ",b;for(b in f)a+=b+'="'+f[b]+'" ';a+="></embed>";f=document.getElementById("equationcomment");f.innerHTML=a;if(f=document.getElementById("eqcoderaw"))f.value=a}function AC_FL_RunContent(){var a=AC_GetArgs(arguments,".swf","movie","clsid:d27cdb6e-ae6d-11cf-96b8-444553540000","application/x-shockwave-flash");AC_Generateobj(a.objAttrs,a.params,a.embedAttrs)}
function AC_SW_RunContent(){var a=AC_GetArgs(arguments,".dcr","src","clsid:166B1BCA-3F9C-11CF-8075-444553540000",null);AC_Generateobj(a.objAttrs,a.params,a.embedAttrs)}
function AC_GetArgs(a,d,f,b,g){for(var e={embedAttrs:{},params:{},objAttrs:{}},c=0;c<a.length;c+=2)switch(a[c].toLowerCase()){case "classid":break;case "pluginspage":e.embedAttrs[a[c]]=a[c+1];break;case "src":case "movie":a[c+1]=AC_AddExtension(a[c+1],d);e.embedAttrs.src=a[c+1];e.params[f]=a[c+1];break;case "onafterupdate":case "onbeforeupdate":case "onblur":case "oncellchange":case "onclick":case "ondblclick":case "ondrag":case "ondragend":case "ondragenter":case "ondragleave":case "ondragover":case "ondrop":case "onfinish":case "onfocus":case "onhelp":case "onmousedown":case "onmouseup":case "onmouseover":case "onmousemove":case "onmouseout":case "onkeypress":case "onkeydown":case "onkeyup":case "onload":case "onlosecapture":case "onpropertychange":case "onreadystatechange":case "onrowsdelete":case "onrowenter":case "onrowexit":case "onrowsinserted":case "onstart":case "onscroll":case "onbeforeeditfocus":case "onactivate":case "onbeforedeactivate":case "ondeactivate":case "type":case "codebase":case "id":e.objAttrs[a[c]]=a[c+
1];break;case "width":case "height":case "align":case "vspace":case "hspace":case "class":case "title":case "accesskey":case "name":case "tabindex":e.embedAttrs[a[c]]=e.objAttrs[a[c]]=a[c+1];break;default:e.embedAttrs[a[c]]=e.params[a[c]]=a[c+1]}e.objAttrs.classid=b;g&&(e.embedAttrs.type=g);return e};