<?php
namespace Chamilo\Core\Repository\ContentObject\Webpage\Table;

use Chamilo\Core\Repository\ContentObject\Webpage\Storage\DataClass\Webpage;
use Chamilo\Libraries\File\Filesystem;
use Chamilo\Libraries\Format\Table\Column\DataClassPropertyTableColumn;
use Chamilo\Libraries\Format\Table\Column\TableColumn;
use Chamilo\Libraries\Format\Table\TableResultPosition;

/**
 * @package Chamilo\Core\Repository\ContentObject\Webpage\Tables
 * @author  Hans De Bisschop <hans.de.bisschop@ehb.be>
 */
class ContentObjectTableRenderer extends \Chamilo\Core\Repository\Table\ContentObjectTableRenderer
{
    protected function initializeColumns()
    {
        $this->addColumn(new DataClassPropertyTableColumn(Webpage::class, Webpage::PROPERTY_EXTENSION));
        $this->addColumn(new DataClassPropertyTableColumn(Webpage::class, Webpage::PROPERTY_FILESIZE));

        parent::initializeColumns();
    }

    /**
     * @param \Chamilo\Libraries\Format\Table\Column\TableColumn $column
     * @param \Chamilo\Libraries\Format\Table\TableResultPosition $resultPosition
     * @param \Chamilo\Core\Repository\ContentObject\Webpage\Storage\DataClass\Webpage $contentObject
     *
     * @return string
     * @throws \Exception
     */
    protected function renderCell(TableColumn $column, TableResultPosition $resultPosition, $contentObject): string
    {
        if ($column->get_name() == Webpage::PROPERTY_FILESIZE)
        {
            return Filesystem::format_file_size($contentObject->get_filesize());
        }

        return parent::renderCell($column, $resultPosition, $contentObject); // TODO: Change the autogenerated stub
    }

}