var clientPC=navigator.userAgent.toLowerCase(),is_gecko=/gecko/.test(clientPC)&&!/khtml|spoofer|netscape\/7\.0/.test(clientPC),webkit_match=clientPC.match(/applewebkit\/(\d+)/);if(webkit_match)var is_safari=-1!=clientPC.indexOf("applewebkit")&&-1==clientPC.indexOf("spoofer"),is_safari_win=is_safari&&-1!=clientPC.indexOf("windows"),webkit_version=parseInt(webkit_match[1]);
var is_ff2=/firefox\/[2-9]|minefield\/3/.test(clientPC),ff2_bugs=/firefox\/2/.test(clientPC),is_ff2_win=is_ff2&&-1!=clientPC.indexOf("windows"),is_ff2_x11=is_ff2&&-1!=clientPC.indexOf("x11");if(-1!=clientPC.indexOf("opera"))var is_opera=!0,is_opera_preseven=window.opera&&!document.childNodes,is_opera_seven=window.opera&&document.childNodes,is_opera_95=/opera\/(9\.[5-9]|[1-9][0-9])/.test(clientPC),opera6_bugs=is_opera_preseven,opera7_bugs=is_opera_seven&&!is_opera_95,opera95_bugs=/opera\/(9\.5)/.test(clientPC);
var doneOnloadHook;if(!window.onloadFuncts)var onloadFuncts=[];function addOnloadHook(a){doneOnloadHook?a():onloadFuncts[onloadFuncts.length]=a}function hookEvent(a,b){addHandler(window,a,b)}function importScript(a){a=wgScript+"?title="+encodeURIComponent(a.replace(/ /g,"_")).replace(/%2F/ig,"/").replace(/%3A/ig,":")+"&action=raw&ctype=text/javascript";return importScriptURI(a)}var loadedScripts={};
function importScriptURI(a){if(loadedScripts[a])return null;loadedScripts[a]=!0;var b=document.createElement("script");b.setAttribute("src",a);b.setAttribute("type","text/javascript");document.getElementsByTagName("head")[0].appendChild(b);return b}function importStylesheet(a){return importStylesheetURI(wgScript+"?action=raw&ctype=text/css&title="+encodeURIComponent(a.replace(/ /g,"_")))}
function importStylesheetURI(a,b){var c=document.createElement("link");c.type="text/css";c.rel="stylesheet";c.href=a;b&&(c.media=b);document.getElementsByTagName("head")[0].appendChild(c);return c}function appendCSS(a){var b=document.createElement("style");b.type="text/css";b.rel="stylesheet";b.styleSheet?b.styleSheet.cssText=a:b.appendChild(document.createTextNode(a+""));document.getElementsByTagName("head")[0].appendChild(b);return b}
"undefined"!=typeof stylepath&&"undefined"!=typeof skin&&(opera6_bugs?importStylesheetURI(stylepath+"/"+skin+"/Opera6Fixes.css"):opera7_bugs?importStylesheetURI(stylepath+"/"+skin+"/Opera7Fixes.css"):opera95_bugs?importStylesheetURI(stylepath+"/"+skin+"/Opera9Fixes.css"):ff2_bugs&&importStylesheetURI(stylepath+"/"+skin+"/FF2Fixes.css"));wgBreakFrames&&window.top!=window&&(window.top.location=window.location);
function showTocToggle(){if(document.createTextNode){var a=document.getElementById("toctitle"),b=document.getElementById("togglelink");if(a&&!b){b=document.createElement("span");b.className="toctoggle";var c=document.createElement("a");c.id="togglelink";c.className="internal";c.href="javascript:toggleToc()";c.appendChild(document.createTextNode(tocHideText));b.appendChild(document.createTextNode("["));b.appendChild(c);b.appendChild(document.createTextNode("]"));a.appendChild(document.createTextNode(" "));
a.appendChild(b);a=document.cookie.indexOf("hidetoc=");a>-1&&document.cookie.charAt(a+8)==1&&toggleToc()}}}function changeText(a,b){if(a.innerText)a.innerText=b;else if(a.firstChild&&a.firstChild.nodeValue)a.firstChild.nodeValue=b}
function toggleToc(){var a=document.getElementById("toc"),b=document.getElementById("toc").getElementsByTagName("ul")[0],c=document.getElementById("togglelink");if(b&&c&&b.style.display=="none"){changeText(c,tocHideText);b.style.display="block";document.cookie="hidetoc=0";a.className="toc"}else{changeText(c,tocShowText);b.style.display="none";document.cookie="hidetoc=1";a.className="toc tochidden"}}var mwEditButtons=[],mwCustomEditButtons=[];
function escapeQuotes(a){var b=RegExp("'","g"),a=a.replace(b,"\\'"),b=RegExp("\\n","g"),a=a.replace(b,"\\n");return escapeQuotesHTML(a)}function escapeQuotesHTML(a){var b=RegExp("&","g"),a=a.replace(b,"&amp;"),b=RegExp('"',"g"),a=a.replace(b,"&quot;"),b=RegExp("<","g"),a=a.replace(b,"&lt;"),b=RegExp(">","g");return a=a.replace(b,"&gt;")}var tooltipAccessKeyPrefix="alt-";
is_opera?tooltipAccessKeyPrefix="shift-esc-":!is_safari_win&&is_safari&&526<webkit_version?tooltipAccessKeyPrefix="ctrl-alt-":!is_safari_win&&(is_safari||-1!=clientPC.indexOf("mac")||-1!=clientPC.indexOf("konqueror"))?tooltipAccessKeyPrefix="ctrl-":is_ff2&&(tooltipAccessKeyPrefix="alt-shift-");var tooltipAccessKeyRegexp=/\[(ctrl-)?(alt-)?(shift-)?(esc-)?(.)\]$/;
function updateTooltipAccessKeys(a){if(a)for(d=0;d<a.length;d++){var b=a[d],c=b.getAttribute("title");if(c&&tooltipAccessKeyRegexp.exec(c)){c=c.replace(tooltipAccessKeyRegexp,"["+tooltipAccessKeyPrefix+"$5]");b.setAttribute("title",c)}}else{var a=["column-one","head","panel","p-logo"],d;for(d in a)(b=document.getElementById(a[d]))&&updateTooltipAccessKeys(b.getElementsByTagName("a"));updateTooltipAccessKeys(document.getElementsByTagName("input"));updateTooltipAccessKeys(document.getElementsByTagName("label"))}}
function addPortletLink(a,b,c,d,g,e,f){var h=document.getElementById(a);if(!h)return null;a=h.getElementsByTagName("ul")[0];if(!a)return null;h.className=h.className.replace(/(^| )emptyPortlet( |$)/,"$2");h=document.createElement("span");h.appendChild(document.createTextNode(c));c=document.createElement("a");c.appendChild(h);c.href=b;b=document.createElement("li");b.appendChild(c);if(d)b.id=d;if(e){c.setAttribute("accesskey",e);g=g+(" ["+e+"]")}g&&c.setAttribute("title",g);e&&g&&updateTooltipAccessKeys(Array(c));
f&&f.parentNode==a?a.insertBefore(b,f):a.appendChild(b);return b}function getInnerText(a){if(typeof a=="string"||typeof a=="undefined")return a;if(a.textContent)return a.textContent;if(a.innerText)return a.innerText;for(var b="",a=a.childNodes,c=a.length,d=0;d<c;d++)switch(a[d].nodeType){case 1:b=b+ts_getInnerText(a[d]);break;case 3:b=b+a[d].nodeValue}return b}
function akeytt(a){if(!window.ta)window.ta=[];var a=a?[a]:window.ta,b=document.getElementById("wpWatchthis")?true:false,c;for(c in a){var d=document.getElementById(c);if(d){var g=null,e="";if(a[c][0].length>0){if((g=d.nodeName.toLowerCase()=="a"?d:d.childNodes[0])&&(c!="ca-watch"&&c!="ca-unwatch"||!b)){g.accessKey=a[c][0];e=" ["+tooltipAccessKeyPrefix+a[c][0]+"]"}}else{g=d;e=""}if(g)g.title=a[c][1]+e}}}var checkboxes,lastCheckbox;
function setupCheckboxShiftClick(){checkboxes=[];lastCheckbox=null;var a=document.getElementsByTagName("input");addCheckboxClickHandlers(a)}function addCheckboxClickHandlers(a,b){b||(b=0);var c=b+250;if(c>a.length)c=a.length;for(var d=b;d<c;d++){var g=a[d];if(g.type&&g.type.toLowerCase()=="checkbox"){var e=checkboxes.length;checkboxes[e]=g;g.index=e;g.onclick=checkboxClickHandler}}c<a.length&&setTimeout(function(){addCheckboxClickHandlers(a,c)},200)}
function checkboxClickHandler(a){if(typeof a=="undefined")a=window.event;if(!a.shiftKey||lastCheckbox===null){lastCheckbox=this.index;return true}var a=this.checked,b,c;if(this.index<lastCheckbox){b=this.index+1;c=lastCheckbox}else{b=lastCheckbox;c=this.index-1}for(var d=b;d<=c;++d){checkboxes[d].checked=a;if(d>b&&typeof checkboxes[d].onchange=="function")checkboxes[d].onchange()}lastCheckbox=this.index;return true}
function toggle_element_activation(a,b){if(document.getElementById){if(b=="wpUploadFileURL"){var c=document.getElementById("mw-upload-maxfilesize");if(c)c.style.display="none";if(c=document.getElementById("mw-upload-maxfilesize-url"))c.style.display="block"}if(b=="wpUploadFile"){if(c=document.getElementById("mw-upload-maxfilesize-url"))c.style.display="none";if(c=document.getElementById("mw-upload-maxfilesize"))c.style.display="block"}document.getElementById(a).disabled=true;document.getElementById(b).disabled=
false}}function toggle_element_check(a,b){if(document.getElementById){document.getElementById(a).checked=true;document.getElementById(b).checked=false}}
function getElementsByClassName(a,b,c){var d=[];if(typeof a.getElementsByClassName=="function"){a=a.getElementsByClassName(c);if(b=="*")return a;for(c=0;c<a.length;c++)a[c].tagName.toLowerCase()==b.toLowerCase()&&(d[d.length]=a[c]);return d}b=b=="*"&&a.all?a.all:a.getElementsByTagName(b);a=[];if(typeof c=="object")for(var g=0;g<c.length;g++)a[a.length]=RegExp("(^|\\s)"+c[g].replace(/\-/g,"\\-")+"(\\s|$)");else a[a.length]=RegExp("(^|\\s)"+c.replace(/\-/g,"\\-")+"(\\s|$)");for(var e=0;e<b.length;e++){for(var c=
b[e],g=true,f=0;f<a.length;f++)if(!a[f].test(c.className)){g=false;break}g&&(d[d.length]=c)}return d}function redirectToFragment(a){var b=navigator.userAgent.match(/AppleWebKit\/(\d+)/);if(!(b&&parseInt(b[1])<420))if(is_gecko)addOnloadHook(function(){if(window.location.hash=="")window.location.hash=a});else if(window.location.hash=="")window.location.hash=a}
var ts_image_path=stylepath+"/common/images/",ts_image_up="sort_up.gif",ts_image_down="sort_down.gif",ts_image_none="sort_none.gif",ts_europeandate="en"!=wgContentLanguage,ts_alternate_row_colors=!1,ts_number_transform_table=null,ts_number_regex=null;function sortables_init(){for(var a=0,b=getElementsByClassName(document,"table","sortable"),c=0;c<b.length;c++){if(!b[c].id){b[c].setAttribute("id","sortable_table_id_"+a);++a}ts_makeSortable(b[c])}}
function ts_makeSortable(a){var b;a.rows&&a.rows.length>0&&(b=a.tHead&&a.tHead.rows.length>0?a.tHead.rows[a.tHead.rows.length-1]:a.rows[0]);if(b){for(var c=0;c<b.cells.length;c++){var d=b.cells[c];if((" "+d.className+" ").indexOf(" unsortable ")==-1)d.innerHTML=d.innerHTML+('&nbsp;&nbsp;<a href="#" class="sortheader" onclick="ts_resortTable(this);return false;"><span class="sortarrow"><img src="'+ts_image_path+ts_image_none+'" alt="&darr;"/></span></a>')}ts_alternate_row_colors&&ts_alternate(a)}}
function ts_getInnerText(a){return getInnerText(a)}
function ts_resortTable(a){for(var b=a.getElementsByTagName("span")[0],c=a.parentNode,a=c.parentNode,d=c.cellIndex,c=a.parentNode;c&&!(c.tagName&&c.tagName.toLowerCase()=="table");)c=c.parentNode;if(c&&!(c.rows.length<=1)){ts_number_transform_table==null&&ts_initTransformTable();for(var g=c.tHead&&c.tHead.rows.length>0?0:1,e="",f=g;f<c.rows.length;f++)if(c.rows[f].cells.length>d){e=ts_getInnerText(c.rows[f].cells[d]);e=e.replace(/^[\s\xa0]+/,"").replace(/[\s\xa0]+$/,"");if(e!="")break}var f=ts_sort_generic,
h=ts_toLowerCase;/^\d\d[\/. -][a-zA-Z]{3}[\/. -]\d\d\d\d$/.test(e)?h=ts_dateToSortKey:/^\d\d[\/.-]\d\d[\/.-]\d\d\d\d$/.test(e)?h=ts_dateToSortKey:/^\d\d[\/.-]\d\d[\/.-]\d\d$/.test(e)?h=ts_dateToSortKey:/(^[\u00a3$\u20ac\u00a4\u00a5]|\u00a2$)/.test(e)?h=ts_currencyToSortKey:ts_number_regex.test(e)&&(h=ts_parseFloat);for(var m=b.getAttribute("sortdir")=="down",e=[],l=[],j=g;j<c.rows.length;j++){var i=c.rows[j];if((" "+i.className+" ").indexOf(" unsortable ")<0){var k=ts_getInnerText(i.cells[d]);k==
void 0&&(k="");var n=m?-j:j,k=h(k.replace(/^[\s\xa0]+/,"").replace(/[\s\xa0]+$/,""));e[e.length]=[i,k,n]}else l[l.length]=[i,false,j-g]}e.sort(f);if(m){d='<img src="'+ts_image_path+ts_image_down+'" alt="&darr;"/>';e.reverse();b.setAttribute("sortdir","up")}else{d='<img src="'+ts_image_path+ts_image_up+'" alt="&uarr;"/>';b.setAttribute("sortdir","down")}for(f=0;f<l.length;f++){i=l[f];e.splice(i[2],0,i)}for(f=0;f<e.length;f++)(" "+e[f][0].className+" ").indexOf(" sortbottom ")==-1&&c.tBodies[0].appendChild(e[f][0]);
for(f=0;f<e.length;f++)(" "+e[f][0].className+" ").indexOf(" sortbottom ")!=-1&&c.tBodies[0].appendChild(e[f][0]);a=getElementsByClassName(a,"span","sortarrow");for(f=0;f<a.length;f++)a[f].innerHTML='<img src="'+ts_image_path+ts_image_none+'" alt="&darr;"/>';b.innerHTML=d;ts_alternate_row_colors&&ts_alternate(c)}}
function ts_initTransformTable(){if(typeof wgSeparatorTransformTable=="undefined"||wgSeparatorTransformTable[0]==""&&wgDigitTransformTable[2]==""){digitClass="[0-9,.]";ts_number_transform_table=false}else{ts_number_transform_table={};ascii=wgSeparatorTransformTable[0].split("\t");localised=wgSeparatorTransformTable[1].split("\t");for(var a=0;a<ascii.length;a++)ts_number_transform_table[localised[a]]=ascii[a];ascii=wgDigitTransformTable[0].split("\t");localised=wgDigitTransformTable[1].split("\t");
for(a=0;a<ascii.length;a++)ts_number_transform_table[localised[a]]=ascii[a];digits=["0","1","2","3","4","5","6","7","8","9",",","\\."];maxDigitLength=1;for(var b in ts_number_transform_table){digits.push(b.replace(/[\\\\$\*\+\?\.\(\)\|\{\}\[\]\-]/,function(a){return"\\"+a}));if(b.length>maxDigitLength)maxDigitLength=b.length}digitClass=maxDigitLength>1?"["+digits.join("",digits)+"]":"("+digits.join("|",digits)+")"}ts_number_regex=RegExp("^([+-]?[0-9][0-9,]*(\\.[0-9,]*)?(E[+-]?[0-9][0-9,]*)?|[+-]?"+
digitClass+"+%?)$","i")}function ts_toLowerCase(a){return a.toLowerCase()}
function ts_dateToSortKey(a){if(a.length==11){switch(a.substr(3,3).toLowerCase()){case "jan":var b="01";break;case "feb":b="02";break;case "mar":b="03";break;case "apr":b="04";break;case "may":b="05";break;case "jun":b="06";break;case "jul":b="07";break;case "aug":b="08";break;case "sep":b="09";break;case "oct":b="10";break;case "nov":b="11";break;case "dec":b="12"}return a.substr(7,4)+b+a.substr(0,2)}if(a.length==10)return ts_europeandate==false?a.substr(6,4)+a.substr(0,2)+a.substr(3,2):a.substr(6,
4)+a.substr(3,2)+a.substr(0,2);if(a.length==8){yr=a.substr(6,2);yr=parseInt(yr)<50?"20"+yr:"19"+yr;return ts_europeandate==true?yr+a.substr(3,2)+a.substr(0,2):yr+a.substr(0,2)+a.substr(3,2)}return"00000000"}function ts_parseFloat(a){if(!a)return 0;if(ts_number_transform_table!=false){for(var b="",c,d=0;d<a.length;d++){c=a.charAt(d);b=c in ts_number_transform_table?b+ts_number_transform_table[c]:b+c}a=b}num=parseFloat(a.replace(/,/g,""));return isNaN(num)?0:num}
function ts_currencyToSortKey(a){return ts_parseFloat(a.replace(/[^0-9.,]/g,""))}function ts_sort_generic(a,b){return a[1]<b[1]?-1:a[1]>b[1]?1:a[2]-b[2]}function ts_alternate(a){for(var a=a.getElementsByTagName("tbody"),b=0;b<a.length;b++)for(var c=a[b].getElementsByTagName("tr"),d=0;d<c.length;d++){for(var g=c[d].className.split(" "),e="",f=0;f<g.length;f++)g[f]!=""&&(g[f]!="even"&&g[f]!="odd")&&(e=e+(g[f]+" "));c[d].className=e+(d%2==0?"even":"odd")}}
function jsMsg(a,b){if(!document.getElementById)return false;var c=document.getElementById("mw-js-message");if(!c){c=document.createElement("div");if(document.getElementById("column-content")&&document.getElementById("content"))document.getElementById("content").insertBefore(c,document.getElementById("content").firstChild);else if(document.getElementById("content")&&document.getElementById("article"))document.getElementById("article").insertBefore(c,document.getElementById("article").firstChild);
else return false}c.setAttribute("id","mw-js-message");c.style.display="block";b&&c.setAttribute("class","mw-js-message-"+b);if(typeof a==="object"){for(;c.hasChildNodes();)c.removeChild(c.firstChild);c.appendChild(a)}else c.innerHTML=a;return true}function injectSpinner(a,b){var c=document.createElement("img");c.id="mw-spinner-"+b;c.src=stylepath+"/common/images/spinner.gif";c.alt=c.title="...";a.nextSibling?a.parentNode.insertBefore(c,a.nextSibling):a.parentNode.appendChild(c)}
function removeSpinner(a){(a=document.getElementById("mw-spinner-"+a))&&a.parentNode.removeChild(a)}function runOnloadHook(){if(!doneOnloadHook&&document.getElementById&&document.getElementsByTagName){doneOnloadHook=true;updateTooltipAccessKeys(null);akeytt(null);setupCheckboxShiftClick();sortables_init();for(var a=0;a<onloadFuncts.length;a++)onloadFuncts[a]()}}function addHandler(a,b,c){window.addEventListener?a.addEventListener(b,c,false):window.attachEvent&&a.attachEvent("on"+b,c)}
function addClickHandler(a,b){addHandler(a,"click",b)}function removeHandler(a,b,c){window.removeEventListener?a.removeEventListener(b,c,false):window.detachEvent&&a.detachEvent("on"+b,c)}hookEvent("load",runOnloadHook);