<?php
namespace Chamilo\Core\Repository\Implementation\Wikimedia\Table\ExternalObjectGallery;

use Chamilo\Core\Repository\External\Table\ExternalObjectGallery\DefaultExternalObjectGalleryTableDataProvider;

class ExternalObjectGalleryObjectTableDataProvider extends DefaultExternalObjectGalleryTableDataProvider
{
}
