<?php
namespace Chamilo\Core\Reporting;

use Chamilo\Configuration\Service\Consulter\ConfigurationConsulter;
use Exception;

/**
 * Class stores style of a reporting template.
 *
 * @package reporting.lib
 * @author  Andras Zolnay
 *         Configuration (PDF) Reports: Administrators can configure PDF reports centrally via Administration ->
 *         Settings -> Reporting. @see
 *         src/Chamilo/Core/Reporting/Resources/Settings/settings.xml. Individual reporing templates and blocks can
 *         override the central settings
 *         and define own style.
 *         Customizing (PDF) Reports:
 *         - Report (sub)title: In order to generate report title, the class name of the concrete reporting template
 *         (derived from ReportingTemplate)
 *         is translated in the context of the template. Block titles are also generated by translating the block class
 *         name (derived from
 *         ReportingBlock).
 *         - Report logo: Logo included in reports can be customized in
 *         Chamilo/Configuration/Resources/Images/<Theme>/LogoReport.png.
 *         - PDF report orientation: By overriding the function getStyle() in concrete reporing template classes,
 *         templates can return an
 *         ReportingTemplateStyle object with custom propery values. Among others the paper orientation property can be
 *         set.
 *         - Report column styles: Concrete reporting templates and blocks can overrule the configured style. In
 *         reporting blocks ReportingDataStyle
 *         ojects can be assigned to data rows. The following example shows how to define the heading colors and define
 *         the column widths:
 *         $style = new ReportingDataStyle();
 *         $style->getHeadingCellStyle()->setTextColor(array(255, 255, 255));
 *         $style->getHeadingCellStyle()->setBackgroundColor(array(150, 150, 150));
 *         $style->setRelativeWidth(0.2);
 *         $reportingData->add_row(Translation::get('Title'), $style);
 *         $style->setRelativeWidth(0.15);
 *         $reportingData->add_row(Translation::get('NumberOfSubmissions'), $style);
 */
class ReportingTemplateStyle
{

    /**
     * Template header font specification
     *
     * @var array(family, style, size)
     *      - family: name of installed font, e.g. 'Arial'.
     *      - style: either empty or combination of 'B', 'I', 'U' or empty string.
     *      - size: font size, e.g. 10.
     */
    private $headerFont = ['Arial', 'B', 11];

    /**
     * Header seprator line color
     *
     * @var array(r [0..255], g [0..255], b [0..255])
     */
    private $headerLineColor = [0, 0, 0];

    /**
     * Title text color
     *
     * @var array(r [0..255], g [0..255], b [0..255])
     */
    private $headerTextColor = [0, 0, 0];

    /**
     * Paper orientation of template
     *
     * @var 'L' or 'P'.
     */
    private $paperOrientation;

    public function __construct(ConfigurationConsulter $configurationConsulter)
    {
        $this->setPaperOrientation(
            $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'paper_orientation'])
        );

        $this->setHeaderTextColor(
            $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_header_text_color'])
        );
        $this->setHeaderFont(
            [
                $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_header_font_family']),
                $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_header_font_style']),
                $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_header_font_size'])
            ]
        );
        $this->setHeaderLineColor(
            $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_header_line_color'])
        );

        $this->setFooterTextColor(
            $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_footer_text_color'])
        );
        $this->setFooterFont(
            [
                $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_footer_font_family']),
                $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_footer_font_style']),
                $configurationConsulter->getSetting(['Chamilo\Core\Reporting', 'template_footer_font_size'])
            ]
        );
    }

    // setter and getter functions

    public function getFooterFont($font = null)
    {
        return $this->footerFont;
    }

    public function getFooterTextColor($color = null)
    {
        return $this->footerTextColor;
    }

    public function getHeaderFont($font = null)
    {
        return $this->headerFont;
    }

    public function getHeaderLineColor($color = null)
    {
        return $this->headerLineColor;
    }

    public function getHeaderTextColor($color = null)
    {
        return $this->headerTextColor;
    }

    public function getPaperOrientation()
    {
        return $this->paperOrientation;
    }

    /**
     * \brief Parses R, G, B values.
     *
     * @param $color - Can be a string: e.g. '255, 255, 255'
     *               - Can be an array: e.g. [255, 255, 255]
     *
     * @return array: e.g. [255, 255, 255].
     */
    public static function parseColor($color)
    {
        $color_array = $color;
        if (!is_array($color_array))
        {
            $color_array = explode(',', $color_array);
        }

        if (count($color_array) != 3)
        {
            throw new Exception('Invalid color: "' . implode(', ', $color_array) . '".');
        }

        return array_map('intval', $color_array);
    }

    /**
     * \brief Parses font Family, Style, Size values.
     *
     * @param $font - Can be an array of strings: e.g. ['Arial', 'B', '10']
     *
     * @return array: e.g. ['Arial', 'B', 10]
     */
    public static function parseFont($font)
    {
        if (count($font) != 3)
        {
            throw new Exception('Invalid font: "' . implode(', ', $font) . '".');
        }

        $result = [];

        $result[] = trim($font[0]);
        $result[] = trim($font[1]);
        $result[] = intval($font[2]);

        return $result;
    }

    public function setFooterFont($font)
    {
        $this->footerFont = ReportingTemplateStyle::parseFont($font);
    }

    public function setFooterTextColor($color)
    {
        $this->footerTextColor = ReportingTemplateStyle::parseColor($color);
    }

    public function setHeaderFont($font)
    {
        $this->headerFont = ReportingTemplateStyle::parseFont($font);
    }

    public function setHeaderLineColor($color)
    {
        $this->headerLineColor = ReportingTemplateStyle::parseColor($color);
    }

    public function setHeaderTextColor($color)
    {
        $this->headerTextColor = ReportingTemplateStyle::parseColor($color);
    }

    public function setPaperOrientation($paperOrientation)
    {
        $this->paperOrientation = $paperOrientation;
    }
}